// Generated by Skyramp v1.3.24 on 2026-05-19 18:27:36.226031638 +0000 UTC m=+485.217845914
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output cart_empty_escape_ui_test.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/cart_empty_escape_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080/cart");
    await page.goto("http://localhost:8080/product/1YMWWN1N4O");
    await page.getByRole("button", { name: "Add To Cart" }).click();
    await page.getByRole("button", { name: "Empty Cart" }).click();
    await page.keyboard.press("Escape");
    await expect(page.getByTestId("cart-heading")).toContainText("Cart (1)");
    await expect(page.getByRole("button", { name: "Empty Cart" })).toBeVisible();
    expect(errors).toHaveLength(0);
});
