// Generated by Skyramp v1.3.24 on 2026-05-21 17:44:19.332090975 +0000 UTC m=+907.107919364
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output product_zoom_currency_regression_ui_test.spec.ts \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/product_zoom_currency_regression_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(60000);
    const errors: Error[] = [];
    page.on('pageerror', (error) => errors.push(error));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080");
    await expect(page.getByRole('heading', { name: 'Hot Products', level: 3 })).toHaveText('Hot Products');

    await page.getByRole("combobox").selectOption("EUR");
    await expect(page.getByRole("combobox")).toHaveValue("EUR");

    await page.goto("http://localhost:8080/product/2ZYFJ3GM2N");
    await expect(page.getByRole('heading', { name: 'Hairdryer', level: 2 })).toHaveText('Hairdryer');
    await expect(page.getByRole('button', { name: 'Add To Cart' })).toBeVisible();

    await page.getByRole("main").hover();
    await expect(page.locator('#product-image')).toHaveClass(/zoom-image/);
    await expect(errors).toHaveLength(0);
});
