// Generated by Skyramp v1.3.24 on 2026-05-21 17:37:02.287884861 +0000 UTC m=+470.063713290
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output-dir /home/runner/work/microservices-demo-testb/microservices-demo-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/microservices-demo-testb/microservices-demo-testb/.skyramp/product_zoom_feature_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(690000);
    const errors: Error[] = [];
    page.on('pageerror', (error) => errors.push(error));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080");
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.goto("http://localhost:8080/product/OLJCESPC7Z");
    await expect(page.getByRole('heading', { name: 'Sunglasses', level: 2 })).toHaveText('Sunglasses');
    await page.getByRole("main").hover();
    await expect(page.locator('#product-image')).toHaveClass(/zoom-image/);
    await page.goto("http://localhost:8080/product/66VCHSJNUP");
    await expect(page.getByRole('heading', { name: 'Tank Top', level: 2 })).toHaveText('Tank Top');
    await page.getByRole("button", { name: "Add To Cart" }).click();
    await expect(page.getByTestId("cart-heading")).toContainText("Cart (1)");
    await expect(page.getByRole('heading', { name: 'Cart (1)', level: 3 })).toHaveText('Cart (1)');
    await expect(page.getByRole('heading', { name: 'Tank Top', level: 4 })).toHaveText('Tank Top');
    await page.goto("http://localhost:8080/product/1YMWWN1N4O");
    await expect(page.getByRole('heading', { name: 'Watch', level: 2 })).toHaveText('Watch');
    await expect(page.getByRole('button', { name: 'Add To Cart' })).toBeVisible();
    await expect(page.locator('#product-image')).toHaveClass(/zoom-image/);
    await expect(errors).toHaveLength(0);
});
